language: c

git:
  depth: 1
  quiet: true
  submodules: false

os:
  - osx

jobs:
  include:
    - name: "macOS 11 universal"
      osx_image: xcode12u
      env:
        - CC='xcrun -sdk macosx11.0 clang -arch arm64 -arch x86_64'
        - EXTRA_LDFLAGS='-mmacosx-version-min=11.0'
    - name: "macOS latest"
      osx_image: xcode12u
    - name: "macOS 10.14"
      osx_image: xcode11
    - name: "macOS oldest"
      osx_image: xcode7.3
    - name: "macOS 32bit"
      env: CC='cc -m32'
    - name: "macOS default (10.13 with Xcode 9.4.1)"

before_script:
  - if [ "$TRAVIS_OS_NAME" = osx ]; then ci/add-osx-cert.sh; fi

script:
  - make bin/sljit_test
  - bin/sljit_test -s
  - codesign -s "$CERTIFICATE_ID" --timestamp --entitlements doc/apple/default.ent -o runtime bin/sljit_test
  - bin/sljit_test -s
