language: c

git:
  depth: 1
  quiet: true
  submodules: false

os:
  - osx

jobs:
  include:
    - name: "macOS 11 universal"
      osx_image: xcode12u
      env:
        - CC='xcrun -sdk macosx11.0 clang -arch arm64 -arch x86_64'
        - EXTRA_LDFLAGS='-mmacosx-version-min=11.0'
    - name: "macOS latest"
      osx_image: xcode12u
    - name: "macOS 10.14"
      osx_image: xcode11
    - name: "macOS default"

script:
  - make bin/sljit_test
  - bin/sljit_test -s
