name: Actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test-on-x86:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Packages
      run: |
        sudo apt -qq update
        sudo apt install -y gcc-multilib make
    - name: Build x86
      env:
        CC: gcc -m32
      run: |
        make all
    - name: Run Tests
      run: |
        ./bin/sljit_test -v

  build-test-on-x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install Packages
      run: |
        sudo apt -qq update
        sudo apt install -y gcc make
    - name: Build x64
      run: |
        make all
    - name: Run Tests
      run: |
        ./bin/sljit_test -v

  build-test-on-loongarch64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Install compiler
      run: |
        sudo apt -qq update
        sudo apt install -y make wget
        wget https://github.com/loongson/build-tools/releases/download/2024.11.01/x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
        tar -xvf x86_64-cross-tools-loongarch64-binutils_2.43.1-gcc_14.2.0-glibc_2.40.tar.xz
    - name: Install qemu
      run: |
        wget https://github.com/loongson/build-tools/releases/download/2024.11.01/qemu-loongarch64
        chmod a+x qemu-loongarch64
    - name: Build and test
      env:
        CROSS_COMPILER: ./cross-tools/bin/loongarch64-unknown-linux-gnu-gcc-14.2.0
        CFLAGS: -march=la464
        EXTRA_LDFLAGS: -static
      run: |
        make all
        ./qemu-loongarch64 ./bin/sljit_test -v
