name: C/C++ CI

on:
  push:
    branches:
    - master
    path-ignore:
    - 'ci/*'
    - 'doc/**'
    - 'README'
    - '*_CHANGES'
  pull_request:
    branches:
    - master
    - integration

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: prepare
      run: ci/prepare.sh
    - name: check
      run: ci/run.sh
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: check
      shell: cmd
      run: |
        gcc -DSLJIT_CONFIG_AUTO=1 -Isljit_src -O2 -Wall test_src/sljitMain.c test_src/sljitTest.c sljit_src/sljitLir.c sljit_src/sljitUtils.c -o sljit_test -lm -lpthread
        sljit_test -s
